### ISSUE TITLE
Verify NSNumber only filters

### ISSUE THREAD

**Issue by nikolaydymura** [nikolaydymura/flutter_core_image_filters#53]
- [ ] Bicubic Scale Transform			`CIBicubicScaleTransform`
- [x] Bloom			`CIBloom`
- [x] Bokeh Blur			`CIBokehBlur`
- [x] Box Blur			`CIBoxBlur`
- [x] Color Controls			`CIColorControls`
- [x] Color Invert			`CIColorInvert`
- [x] Color Posterize			`CIColorPosterize`
- [x] Color Threshold			`CIColorThreshold`
- [x] Color Threshold Otsu			`CIColorThresholdOtsu`
- [x] Comic Effect			`CIComicEffect`
- [ ] Convert Lab to RGB			`CIConvertLabToRGB`
- [x] Convert RGB to Lab			`CIConvertRGBtoLab`
- [ ] Depth To Disparity			`CIDepthToDisparity`
- [x] Disc Blur			`CIDiscBlur`
- [ ] Disparity To Depth			`CIDisparityToDepth`
- [x] Dither			`CIDither`
- [x] Document Enhancer			`CIDocumentEnhancer`
- [x] Edges			`CIEdges`
- [ ] Edge Work			`CIEdgeWork`
- [x] Exposure Adjust			`CIExposureAdjust`
- [x] Gabor Gradients			`CIGaborGradients`
- [x] Gamma Adjust			`CIGammaAdjust`
- [x] Gaussian Blur			`CIGaussianBlur`
- [x] Gloom			`CIGloom`
- [x] Height Field From Mask			`CIHeightFieldFromMask`
- [x] Highlight and Shadow Adjust			`CIHighlightShadowAdjust`
- [x] Histogram Display			`CIHistogramDisplayFilter`
- [x] Hue Adjust			`CIHueAdjust`
- [x] Lanczos Scale Transform			`CILanczosScaleTransform`
- [x] Linear to sRGB Tone Curve			`CILinearToSRGBToneCurve`
- [x] Line Overlay			`CILineOverlay`
- [ ] Mask to Alpha			`CIMaskToAlpha`
- [x] Maximum Component			`CIMaximumComponent`
- [x] Median			`CIMedianFilter`
- [x] Minimum Component			`CIMinimumComponent`
- [x] Morphology Gradient			`CIMorphologyGradient`
- [x] Morphology Maximum			`CIMorphologyMaximum`
- [x] Morphology Minimum			`CIMorphologyMinimum`
- [x] Morphology Rectangle Maximum			`CIMorphologyRectangleMaximum`
- [x] Morphology Rectangle Minimum			`CIMorphologyRectangleMinimum`
- [x] Motion Blur			`CIMotionBlur`
- [x] Noise Reduction			`CINoiseReduction`
- [ ] Person Segmentation			`CIPersonSegmentation`
- [x] Perspective Rotate			`CIPerspectiveRotate`
- [x] Photo Effect Chrome			`CIPhotoEffectChrome`
- [x] Photo Effect Fade			`CIPhotoEffectFade`
- [x] Photo Effect Instant			`CIPhotoEffectInstant`
- [x] Photo Effect Mono			`CIPhotoEffectMono`
- [x] Photo Effect Noir			`CIPhotoEffectNoir`
- [x] Photo Effect Process			`CIPhotoEffectProcess`
- [x] Photo Effect Tonal			`CIPhotoEffectTonal`
- [x] Photo Effect Transfer			`CIPhotoEffectTransfer`
- [ ] Random Generator			`CIRandomGenerator`
- [ ] Saliency Map Filter			`CISaliencyMapFilter`
- [x] Sample Nearest			`CISampleNearest`
- [x] Sepia Tone			`CISepiaTone`
- [x] Sharpen Luminance			`CISharpenLuminance`
- [x] sRGB Tone Curve to Linear			`CISRGBToneCurveToLinear`
- [x] Straighten			`CIStraightenFilter`
- [x] Thermal			`CIThermal`
- [x] Unsharp Mask			`CIUnsharpMask`
- [x] Vibrance			`CIVibrance`
- [x] Vignette			`CIVignette`
- [x] X-Ray			`CIXRay`

**Comment by nataliiazabiiaka** [comment]
Bicubic Scale Transform CIBicubicScaleTransform - scale (-);
Convert Lab to RGB CIConvertLabToRGB, Person Segmentation CIPersonSegmentation - don't see this filter;
Depth To Disparity, Disparity To Depth - only red container;
Edge Work CIEdgeWork, Saliency Map Filter - too light;
Mask to Alpha - white  screen;
Random Generator CIRandomGenerator - can't open filter;
