### ISSUE TITLE
Verify NSNumber & CIColor filters

### ISSUE THREAD

**Issue by nikolaydymura** [nikolaydymura/flutter_core_image_filters#54]
- [x] Color Monochrome			`CIColorMonochrome`
- [x] Constant Color			`CIConstantColorGenerator`
- [x] False Color			`CIFalseColor`
- [ ] Spot Color			`CISpotColor`
- [x] White Point Adjust			`CIWhitePointAdjust`

**Comment by nataliiazabiiaka** [comment]
Constant Color CIConstantColorGenerator - can't open this filter;
False Color CIFalseColor, White Point Adjust CIWhitePointAdjust - only black containers;
Spot Color CISpotColor - don't have this filter;

**Comment by nataliiazabiiaka** [comment]
Spot Color CISpotColor - don't find this filter;
Constant Color CIConstantColorGenerator -  container with only one color
