### ISSUE TITLE
Mark filters as ones have no input image. Look at `CIConstantColorGeneratorConfiguration`

### ISSUE THREAD

**Issue by nikolaydymura** [nikolaydymura/flutter_core_image_filters#62]
`  @override
  bool get hasInputImage => false;` 

 - [x] CIAttributedTextImageGenerator
 - [x] CIAztecCodeGenerator
 - [x] CIBarcodeGenerator
 - [x] CICheckerboardGenerator
 - [x] CICode128BarcodeGenerator
 - [x] CIConstantColorGenerator
 - [x] CIGaussianGradient
 - [x] CIHueSaturationValueGradient
 - [x] CILenticularHaloGenerator
 - [x] CILinearGradient
 - [x] CIMeshGenerator
 - [x] CIPDF417BarcodeGenerator
 - [x] CIQRCodeGenerator
 - [x] CIRadialGradient
 - [x] CIRandomGenerator
 - [x] CIRoundedRectangleGenerator
 - [x] CISmoothLinearGradient
 - [x] CIStarShineGenerator
 - [x] CIStripesGenerator
 - [x] CISunbeamsGenerator
 - [x] CITextImageGenerator

**Comment by nataliiazabiiaka** [comment]
The CIConstantColorGenerator, CITextImageGenerator already had this command;
CIHueSaturationValueGradient, CIMeshGenerator, CIQRCodeGenerator not found;
